// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnyecwelpyyepmqtqwfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRueWVjd2VscHl5ZXBtcXRxd2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MjY1MzQsImV4cCI6MjA3NjEwMjUzNH0.MwVMN3XLUEkiE90_AbjvD_PkxN6u7gEXLYWr0W7Shw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});